[package]
name = "sldkit-container"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
cfb.workspace = true
crc32fast.workspace = true
flate2.workspace = true
sha2.workspace = true
sldkit-core = { path = "../sldkit-core" }

[lints]
workspace = true
