[package]
name = "sldkit-parser"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
crc32fast.workspace = true
roxmltree.workspace = true
sha2.workspace = true
sldkit-container = { path = "../sldkit-container" }
sldkit-core = { path = "../sldkit-core" }

[dev-dependencies]
flate2.workspace = true
tempfile.workspace = true

[lints]
workspace = true
