"""Validate source licensing and exact archive notices (Python 3.11+)."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from email.message import Message
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT_LICENSE = "PolyForm-Noncommercial-1.0.0 AND MIT"
DISTRIBUTION_LICENSE = PROJECT_LICENSE + " AND Apache-2.0 AND BSD-3-Clause"
PARASOLID_VERSION = "0.2.0"
LOCKFILES = (
    "Cargo.lock",
    "vendor/cadmpeg-codec-sldprt/Cargo.lock",
    "fuzz/Cargo.lock",
)
PINNED_TEXTS = {
    "LICENSES/PolyForm-Noncommercial-1.0.0.md": (
        "c0ea4a896d2c8c394b29f9427589996db826cd501c512279ff0ed3ef48fabbe5"
    ),
    "LICENSES/sldkit-legacy-MIT.txt": (
        "41c78a91c904b406db082472b30db9f9f83ce93c5a68c6b26b15735c4e101f5c"
    ),
}
REQUIRED_NOTICES = (
    "Required Notice: sldkit is licensed by UnRobotics Inc. (https://www.un-robotics.com/).",
    "Required Notice: sldkit 0.2.0 and later offer new material under PolyForm "
    "Noncommercial 1.0.0; separate commercial licenses are available.",
)
REQUIRED_FILES = {
    *PINNED_TEXTS,
    "LICENSES/Apache-2.0.txt",
    "LICENSES/parasolid-core-MIT.txt",
    "LICENSES/parasolid-core-PARTIAL_READERS.md",
    "LICENSES/three-MIT.txt",
    "LICENSES/rust-dependencies.json",
    "LICENSES/rust-dependencies.txt",
}
EXCLUSIONS = {
    ("r-efi", "6.0.0"): "UEFI-only dependency; no supported distribution targets UEFI.",
    ("libfuzzer-sys", "0.4.13"): (
        "Fuzz-only build tool (including the NCSA libFuzzer engine); "
        "fuzz sources and the engine are not bundled in wheels or sdists."
    ),
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_toml(path: Path) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def license_paths(root: Path = ROOT) -> list[str]:
    paths = ["LICENSE", "COMMERCIAL-LICENSE.md", "THIRD_PARTY_NOTICES.md"]
    paths += [
        p.relative_to(root).as_posix()
        for p in sorted((root / "LICENSES").iterdir())
        if p.is_file() and p.suffix in {".txt", ".md", ".json"}
    ]
    if not REQUIRED_FILES.issubset(paths):
        raise ValueError(
            f"Missing canonical license files: {REQUIRED_FILES - set(paths)}"
        )
    return paths


def check_pinned_texts(read: Callable[[str], bytes]) -> None:
    for path, digest in PINNED_TEXTS.items():
        if sha256(read(path)) != digest:
            raise ValueError(f"Changed canonical license text: {path}")


def notice_bundle(root: Path = ROOT, *, viewer: bool = False) -> bytes:
    paths = (
        ["LICENSE", "COMMERCIAL-LICENSE.md", *PINNED_TEXTS, "LICENSES/three-MIT.txt"]
        if viewer
        else license_paths(root)
    )
    text = (
        "Generated by scripts/sync_license_notices.py; do not edit this copy.\n"
        "Canonical source files are reproduced below. "
        "Relative links refer to the source distribution.\n"
        "Repository: https://github.com/monozukuri-ai/sldkit\n"
    )
    for path in paths:
        text += f"\n===== {path} =====\n\n" + (root / path).read_text(encoding="utf-8")
    return text.encode("utf-8")


def check_archive_licenses(
    read: Callable[[str], bytes], metadata: Message, prefix: str, root: Path = ROOT
) -> None:
    """Require declared paths and bytes, rather than permissive suffix matches."""
    project = read_toml(root / "pyproject.toml")["project"]
    if metadata["Name"] != "sldkit" or metadata["Version"] != project["version"]:
        raise ValueError("Unexpected distribution identity/version")
    if metadata["License-Expression"] != DISTRIBUTION_LICENSE:
        raise ValueError("Unexpected License-Expression")
    if metadata["License"] or any(
        c.startswith("License ::") for c in metadata.get_all("Classifier", [])
    ):
        raise ValueError("Obsolete license metadata")
    declared = metadata.get_all("License-File", [])
    expected = set(license_paths(root))
    if set(declared) != expected or len(declared) != len(expected):
        raise ValueError("Unexpected License-File declarations")
    for path in sorted(expected):
        try:
            actual = read(prefix + path)
        except (KeyError, FileNotFoundError) as exc:
            raise ValueError(f"Missing license/notice: {prefix + path}") from exc
        if actual != (root / path).read_bytes():
            raise ValueError(f"Stale license/notice: {prefix + path}")
    check_pinned_texts(lambda p: read(prefix + p))


def check_viewer_assets(read: Callable[[str], bytes], root: Path = ROOT) -> None:
    expected = notice_bundle(root, viewer=True)
    if read("LICENSE.txt") != expected:
        raise ValueError("Stale viewer license bundle")
    if read("three-LICENSE.txt") != (root / "LICENSES/three-MIT.txt").read_bytes():
        raise ValueError("Stale Three.js notice")
    if not read("viewer.js").startswith(b"/*\n" + expected + b"\n*/"):
        raise ValueError("Missing or stale JavaScript license banner; rebuild viewer")


def locked_packages(root: Path = ROOT) -> dict[tuple[str, str, str], dict]:
    packages: dict[tuple[str, str, str], dict] = {}
    for path in LOCKFILES:
        lock = read_toml(root / path)
        for package in lock["package"]:
            if not package.get("source"):
                continue
            key = package["name"], package["version"], package["source"]
            row = packages.setdefault(key, {**package, "lockfiles": []})
            if row["checksum"] != package["checksum"]:
                raise ValueError(f"Conflicting registry checksums: {key}")
            row["lockfiles"].append(path)
    return packages


def check_catalog(root: Path = ROOT) -> None:
    catalog = json.loads((root / "LICENSES/rust-dependencies.json").read_bytes())
    if catalog["schema_version"] != 1:
        raise ValueError("Unexpected license catalog schema")
    expected = locked_packages(root)
    rows = catalog["packages"] + catalog["excluded"]
    actual = {(p["name"], p["version"], p["source"]): p for p in rows}
    if len(actual) != len(rows) or actual.keys() != expected.keys():
        raise ValueError("Rust notice inventory does not match lockfiles")
    for key, row in actual.items():
        for field in ("checksum", "lockfiles"):
            if row[field] != expected[key][field]:
                raise ValueError(f"Stale dependency {field}: {key}")
    for row in catalog["excluded"]:
        key = row["name"], row["version"]
        if row["reason"] != EXCLUSIONS.get(key):
            raise ValueError(f"Unreviewed notice exclusion: {key}")
        if key[0] == "libfuzzer-sys" and row["lockfiles"] != ["fuzz/Cargo.lock"]:
            raise ValueError("libFuzzer exclusion requires a fuzz-only dependency")
    if (
        sha256((root / "LICENSES/rust-dependencies.txt").read_bytes())
        != catalog["notices_sha256"]
    ):
        raise ValueError("Rust notice catalog hash mismatch")
    for row in catalog["packages"]:
        if not row["license_files"] or not row["selected_license"]:
            raise ValueError(f"Missing license selection/text: {row['name']}")


def check(root: Path = ROOT) -> str:
    check_pinned_texts(lambda p: (root / p).read_bytes())
    for path in ("LICENSE", "README.md"):
        lines = (root / path).read_text(encoding="utf-8").splitlines()
        if not all(notice in lines for notice in REQUIRED_NOTICES):
            raise ValueError(f"Missing Required Notice: {path}")
    project = read_toml(root / "pyproject.toml")["project"]
    workspace = read_toml(root / "Cargo.toml")["workspace"]
    if (
        project["license"] != DISTRIBUTION_LICENSE
        or workspace["package"]["license"] != PROJECT_LICENSE
    ):
        raise ValueError("Unexpected source license expression")
    declared = {
        p.relative_to(root).as_posix()
        for pattern in project["license-files"]
        for p in root.glob(pattern)
        if p.is_file()
    }
    if declared != set(license_paths(root)):
        raise ValueError("pyproject license-files do not cover canonical files")
    for member in workspace["members"]:
        package = read_toml(root / member / "Cargo.toml")["package"]
        if package["license"] != {"workspace": True} or package["readme"] != {
            "workspace": True
        }:
            raise ValueError(f"Crate must inherit license and readme: {member}")
        if (root / member / "LICENSE").read_bytes() != notice_bundle(root):
            raise ValueError(f"Stale crate license bundle: {member}")
    if read_toml(root / "fuzz/Cargo.toml")["package"]["license"] != PROJECT_LICENSE:
        raise ValueError("Unexpected fuzz harness license")
    if (root / "fuzz/LICENSE").read_bytes() != notice_bundle(root):
        raise ValueError("Stale fuzz notice bundle")
    vendor = read_toml(root / "vendor/cadmpeg-codec-sldprt/Cargo.toml")
    if vendor["package"]["license"] != "Apache-2.0":
        raise ValueError("Vendor must retain Apache-2.0")
    if (
        workspace["dependencies"]["parasolid-core"] != "=" + PARASOLID_VERSION
        or vendor["dependencies"]["parasolid-core"]["version"]
        != "=" + PARASOLID_VERSION
    ):
        raise ValueError("Unexpected parasolid-core pin")
    for lock in LOCKFILES:
        versions = [
            p["version"]
            for p in read_toml(root / lock)["package"]
            if p["name"] == "parasolid-core"
        ]
        if versions != [PARASOLID_VERSION]:
            raise ValueError(f"Stale parasolid-core lock: {lock}")
    viewer = json.loads((root / "viewer/package.json").read_bytes())
    npm_lock = json.loads((root / "viewer/package-lock.json").read_bytes())
    for package in (viewer, npm_lock["packages"][""]):
        if (
            package["license"] != PROJECT_LICENSE
            or package["version"] != project["version"]
        ):
            raise ValueError("Unexpected viewer license/version")
    if npm_lock["version"] != project["version"]:
        raise ValueError("Stale npm lock version")
    if (root / "viewer/LICENSE.txt").read_bytes() != notice_bundle(root, viewer=True):
        raise ValueError("Stale viewer source notice")
    assets = root / "python/sldkit/viewer/_assets"
    check_viewer_assets(lambda p: (assets / p).read_bytes(), root)
    check_catalog(root)
    return project["version"]


if __name__ == "__main__":
    print("License checks passed for sldkit " + check())
