def probe_bytes_json(data: bytes, profile: str) -> str: ...
def probe_file_json(path: str, profile: str) -> str: ...
def inspect_bytes_json(data: bytes, filename: str | None, profile: str) -> str: ...
def inspect_file_json(path: str, profile: str) -> str: ...
def parse_bytes_json(data: bytes, filename: str | None, profile: str) -> str: ...
def parse_file_json(path: str, profile: str) -> str: ...
def scan_project_json(
    path: str,
    project_root: str | None,
    configuration: str | None,
    search_directories: list[str],
    windows_prefix_mappings: list[tuple[str, str]],
    follow_suppressed: bool,
    profile: str,
) -> str: ...
def extract_bytes_result(
    data: bytes, entry_id: str, mode: str, profile: str
) -> tuple[str, bytes | None]: ...
def extract_file_result(
    path: str, entry_id: str, mode: str, profile: str
) -> tuple[str, bytes | None]: ...
